export interface Project {
  name: string
  location: string
  slug: string
  cover: string
  images: string[]
}

export const projects: Project[] = [
  {
    name: 'Edgemont Contemporary',
    location: 'Edgemont, NY',
    slug: 'edgemont-contemporary',
    cover: '/projects/edgemont-contemporary/1.jpeg',
    images: [
      '/projects/edgemont-contemporary/1.jpeg',
      '/projects/edgemont-contemporary/2.jpeg',
      '/projects/edgemont-contemporary/3.jpeg',
      '/projects/edgemont-contemporary/4.jpg',
      '/projects/edgemont-contemporary/5.jpg',
      '/projects/edgemont-contemporary/6.jpg',
      '/projects/edgemont-contemporary/7.jpg',
    ],
  },
  {
    name: 'Heathcote Classic',
    location: 'Scarsdale, NY',
    slug: 'heathcote-classic',
    cover: '/projects/heathcote-classic/1.webp',
    images: [
      '/projects/heathcote-classic/1.webp',
      '/projects/heathcote-classic/2.webp',
      '/projects/heathcote-classic/3.webp',
      '/projects/heathcote-classic/4.webp',
      '/projects/heathcote-classic/5.webp',
      '/projects/heathcote-classic/6.webp',
      '/projects/heathcote-classic/7.webp',
      '/projects/heathcote-classic/8.webp',
      '/projects/heathcote-classic/9.webp',
    ],
  },
  {
    name: 'Scarsdale Transitional',
    location: 'Scarsdale, NY',
    slug: 'scarsdale-transitional',
    cover: '/projects/scarsdale-transitional/1.jpg',
    images: [
      '/projects/scarsdale-transitional/1.jpg',
      '/projects/scarsdale-transitional/2.jpg',
      '/projects/scarsdale-transitional/3.jpg',
      '/projects/scarsdale-transitional/4.jpg',
      '/projects/scarsdale-transitional/5.jpg',
      '/projects/scarsdale-transitional/6.jpg',
    ],
  },
  {
    name: 'Mamaroneck Center Hall',
    location: 'Mamaroneck, NY',
    slug: 'mamaroneck-center-hall',
    cover: '/projects/mamaroneck-center-hall/1.jpg',
    images: [
      '/projects/mamaroneck-center-hall/1.jpg',
      '/projects/mamaroneck-center-hall/2.jpg',
      '/projects/mamaroneck-center-hall/3.jpg',
    ],
  },
  {
    name: 'Julia Court Oasis',
    location: 'Westchester, NY',
    slug: 'julia-court-oasis',
    cover: '/projects/julia-court-oasis/1.jpeg',
    images: [
      '/projects/julia-court-oasis/1.jpeg',
      '/projects/julia-court-oasis/2.jpeg',
      '/projects/julia-court-oasis/3.jpeg',
      '/projects/julia-court-oasis/4.jpeg',
      '/projects/julia-court-oasis/5.jpg',
    ],
  },
  {
    name: 'Stonewall "Gables"',
    location: 'Westchester, NY',
    slug: 'stonewall-gables',
    cover: '/projects/stonewall-gables/1.webp',
    images: [
      '/projects/stonewall-gables/1.webp',
      '/projects/stonewall-gables/2.webp',
      '/projects/stonewall-gables/3.webp',
      '/projects/stonewall-gables/4.webp',
      '/projects/stonewall-gables/5.webp',
      '/projects/stonewall-gables/6.webp',
      '/projects/stonewall-gables/7.webp',
    ],
  },
  {
    name: 'Rye Colonial',
    location: 'Rye, NY',
    slug: 'rye-colonial',
    cover: '/projects/rye-colonial/1.jpg',
    images: [
      '/projects/rye-colonial/1.jpg',
      '/projects/rye-colonial/2.jpg',
      '/projects/rye-colonial/3.jpg',
    ],
  },
  {
    name: 'Mamaroneck Modern',
    location: 'Mamaroneck, NY',
    slug: 'mamaroneck-modern',
    cover: '/projects/mamaroneck-modern/1.jpg',
    images: [
      '/projects/mamaroneck-modern/1.jpg',
      '/projects/mamaroneck-modern/2.jpg',
      '/projects/mamaroneck-modern/3.jpg',
      '/projects/mamaroneck-modern/4.jpg',
      '/projects/mamaroneck-modern/5.jpg',
      '/projects/mamaroneck-modern/6.jpg',
      '/projects/mamaroneck-modern/7.jpg',
    ],
  },
  {
    name: 'Scarsdale Tudor',
    location: 'Scarsdale, NY',
    slug: 'scarsdale-tudor',
    cover: '/projects/scarsdale-tudor/1.jpg',
    images: [
      '/projects/scarsdale-tudor/1.jpg',
      '/projects/scarsdale-tudor/2.jpg',
      '/projects/scarsdale-tudor/3.jpg',
      '/projects/scarsdale-tudor/4.jpg',
      '/projects/scarsdale-tudor/5.jpg',
      '/projects/scarsdale-tudor/6.jpg',
      '/projects/scarsdale-tudor/7.jpg',
    ],
  },
  {
    name: 'Eastchester Farmhouse',
    location: 'Eastchester, NY',
    slug: 'eastchester-farmhouse',
    cover: '/projects/eastchester-farmhouse/1.jpeg',
    images: [
      '/projects/eastchester-farmhouse/1.jpeg',
      '/projects/eastchester-farmhouse/2.jpeg',
      '/projects/eastchester-farmhouse/3.jpg',
    ],
  },
  {
    name: 'Edgewood Colonial Addition',
    location: 'Scarsdale, NY',
    slug: 'edgewood-colonial-addition',
    cover: '/projects/edgewood-colonial-addition/1.jpeg',
    images: [
      '/projects/edgewood-colonial-addition/1.jpeg',
      '/projects/edgewood-colonial-addition/2.jpeg',
      '/projects/edgewood-colonial-addition/3.jpeg',
      '/projects/edgewood-colonial-addition/4.jpeg',
    ],
  },
  {
    name: 'Eastchester Side Hall Colonial',
    location: 'Eastchester, NY',
    slug: 'eastchester-side-hall-colonial',
    cover: '/projects/eastchester-side-hall-colonial/1.jpg',
    images: [
      '/projects/eastchester-side-hall-colonial/1.jpg',
      '/projects/eastchester-side-hall-colonial/2.jpg',
    ],
  },
  {
    name: 'Scarsdale Mediterranean',
    location: 'Scarsdale, NY',
    slug: 'scarsdale-mediterranean',
    cover: '/projects/scarsdale-mediterranean/1.jpeg',
    images: [
      '/projects/scarsdale-mediterranean/1.jpeg',
      '/projects/scarsdale-mediterranean/2.jpg',
      '/projects/scarsdale-mediterranean/3.jpg',
      '/projects/scarsdale-mediterranean/4.jpg',
    ],
  },
  {
    name: 'Barry Colonial',
    location: 'Westchester, NY',
    slug: 'barry-colonial',
    cover: '/projects/barry-colonial/4.jpg',
    images: [
      '/projects/barry-colonial/4.jpg',
      '/projects/barry-colonial/1.jpg',
      '/projects/barry-colonial/2.jpg',
      '/projects/barry-colonial/3.jpg',
      '/projects/barry-colonial/5.jpg',
      '/projects/barry-colonial/6.jpg',
    ],
  },
  {
    name: 'Eastchester Colonial Revival',
    location: 'Eastchester, NY',
    slug: 'eastchester-colonial-revival',
    cover: '/projects/eastchester-colonial-revival/4.jpg',
    images: [
      '/projects/eastchester-colonial-revival/4.jpg',
      '/projects/eastchester-colonial-revival/1.jpg',
      '/projects/eastchester-colonial-revival/2.jpg',
      '/projects/eastchester-colonial-revival/3.jpg',
    ],
  },
  {
    name: 'Corell Tudor',
    location: 'Scarsdale, NY',
    slug: 'corell-tudor',
    cover: '/projects/corell-tudor/1.jpg',
    images: ['/projects/corell-tudor/1.jpg'],
  },
  {
    name: 'Cushman Craftsman',
    location: 'Scarsdale, NY',
    slug: 'cushman-craftsman',
    cover: '/projects/cushman-craftsman/1.jpg',
    images: [
      '/projects/cushman-craftsman/1.jpg',
      '/projects/cushman-craftsman/2.jpg',
    ],
  },
  {
    name: 'Edgewood Restoration',
    location: 'Scarsdale, NY',
    slug: 'edgewood-restoration',
    cover: '/projects/edgewood-restoration/1.jpg',
    images: ['/projects/edgewood-restoration/1.jpg'],
  },
  {
    name: 'Murry Shingle',
    location: 'Scarsdale, NY',
    slug: 'murry-shingle',
    cover: '/projects/murry-shingle/1.jpg',
    images: ['/projects/murry-shingle/1.jpg'],
  },
  {
    name: 'Pelham Brick Estate',
    location: 'Pelham, NY',
    slug: 'pelham-brick-estate',
    cover: '/projects/pelham-brick-estate/1.jpg',
    images: [
      '/projects/pelham-brick-estate/1.jpg',
      '/projects/pelham-brick-estate/2.jpg',
      '/projects/pelham-brick-estate/3.jpg',
    ],
  },
  {
    name: 'Wilmot Manor',
    location: 'Scarsdale, NY',
    slug: 'wilmot-manor',
    cover: '/projects/wilmot-manor/1.jpg',
    images: [
      '/projects/wilmot-manor/1.jpg',
      '/projects/wilmot-manor/2.jpg',
      '/projects/wilmot-manor/3.jpg',
      '/projects/wilmot-manor/4.jpg',
    ],
  },
  {
    name: 'Reynal Crossing Tudor',
    location: 'Scarsdale, NY',
    slug: 'reynal-crossing-tudor',
    cover: '/projects/reynal-crossing-tudor/1.jpg',
    images: ['/projects/reynal-crossing-tudor/1.jpg'],
  },
  {
    name: 'Wildwood Colonial',
    location: 'Scarsdale, NY',
    slug: 'wildwood-colonial',
    cover: '/projects/wildwood-colonial/1.jpg',
    images: ['/projects/wildwood-colonial/1.jpg'],
  },
]
